# Application config
database:
  postgres:
    host: localhost
    port: 5432
    base: postgres

    user: postgres
    password: postgres

  mongodb:
    host: localhost
    database: test
