# Spring Profile
spring:
  profiles:
    active: "default"
---
# Spring Boot configuration
spring:
  # Database
  datasource:
    url: jdbc:postgresql://${database.postgres.host}:${database.postgres.port}/${database.postgres.base}
    username: ${database.postgres.user}
    password: ${database.postgres.password}

  # JPA properties
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

# Server configuration
server:
  port: 8080