# Spring Profile
spring:
  profiles:
    active: "development"
---
# Spring Boot configuration
spring:
  profiles: development
  # Database
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:32772/postgres?currentSchema=public
    username: postgres
    password:
    initialization-mode: never
  # JPA properties
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
# Server configuration
server:
  port: 8080